services:
  mongo:
    image: mongo:7
    container_name: campus-mongo
    ports:
      - '27016:27017' # expose mongo on host 27016, keep default container port
    volumes:
      - mongo_data:/data/db
    command: >
      mongod --quiet
      --setParameter logComponentVerbosity='{"command":1}'

  backend:
    build:
      context: ./backend/ # adjust if compose file is not inside backend repo
      target: dev
    container_name: campus-api
    ports:
      - '4000:4000'
    environment:
      PORT: 4000
      MONGO_URI: mongodb://host.docker.internal:27017/campushub-db
      MONGO_MAX_POOL: '50'
      MONGO_MIN_POOL: '0'
      MONGO_MAX_IDLE_MS: '60000'
      MONGO_SST_MS: '8000'
      MONGO_SOCKET_MS: '45000'
      MONGO_APP_NAME: CampusHubAPI
      CORS_ORIGIN: http://localhost:3000
      BETTER_AUTH_SECRET: 188b125ca59d1c3bcc2dc0c0c35eec86798c8ece501c38f3fad676ac144dc096
      BETTER_AUTH_URL: http://localhost:4000
      ALLOWED_EMAIL_DOMAINS: city.ac.uk
      SUPER_USER_EMAIL: muhammad.khan.45@city.ac.uk
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend/
      target: dev
      args:
        API_SPEC_URL: http://campus-api:4000/api-json
    container_name: campus-web
    environment:
      # Often needed on Docker Desktop so file changes are seen
      CHOKIDAR_USEPOLLING: 'true'
      WATCHPACK_POLLING: 'true'
      API_SPEC_URL: "http://campus-api:4000/api-json"
      NEXT_PUBLIC_API_URL: "http://localhost:4000"
      BETTER_AUTH_BASE_URL: "http://localhost:4000"

    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend

volumes:
  mongo_data:
  backend_node_modules:
  frontend_node_modules:
